---
title: "Covid91 vaccine study Final2024"
author: "Put your name here!"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
FinalDat <-read.csv(file="finalSumr2024.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- FinalDat  %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

## Males


## Females


## LGBTQ



## Druggies


# Overall Results and Conclusions


## Male conclusion 

When trying to figure out the effectiveness of the vaccine i males, the bar char shows that you are less likely to contract covid91 if you did receive the vaccine. The numerical data shows the results in percentages. Within the placebo group 73.80% of individuals got infected with covid91. While in the vaccine group 26.20% contracted covid 91. The indicates that receiving the vaccine as a male significantly reduces the risk of contracted covid91. The inferential data shows the Chi-Squared P-Value is 2.2e-16, and the data also showes the Fisher exact test that shows the P-Value is 2.2e-16 which is significantly lower than 0.05 which means we reject the null hypothesis. All in all these examples and simulations show that as a male you are far less
likely to contract covid 91 upon receiving the vaccine.   


## Female Conclusion 

When testing the effectiveness of the vaccine in females, the bar chart shows that you are less likely to contract covid 91 if you receive the vaccine. The numerical data shows the results in percentages. Within the placebo group 64.93% of individuals got infected with covid 91. While in the vaccine group 35.07% contracted covid 91. This indicates that reciving the vaccine as a female significantly reduces the risk of contracted covid 91. The inferential data shows the Chi-Square P-Value of 1.914e-08, and the data also includes the fisher exact test that shows the P-Value is 1.246e-08 which is significantly lower than 0.05 which means we reject the null hypothesis. In summation these examples and simulations show that as a female you are less likely to contract covid 91 if you receive the vaccine.  


## LGBTQ Conclusion 

When testing the effectiveness of the vaccine in members of the LGBTQ community, the bar chart shows that you are less likely to contract covid 91 if you receive the vaccine. The numerical data shows the results in percentages. Within the placebo group 80.00% of individuals got infected with covid 91. While in the vaccine group 20.00% contracted covid 91. This indicates that receiving the vaccine as a LGBTQ member significantly reduces the risk of contracted covid 91. The inferential data shows the Chi-Square P-Value is 2.266e-06, and the data also includes the fisher exact test that shows the P-Value is 7.269e-07 which is significantly lower than 0.05 which means we reject the null hypothesis. In summation these examples and simulations show that as a LGBTQ member you are less likely to contract covid 91 if you receive the vaccine.  

## Drug User Conclusion 

When testing the effectiveness of the vaccine on people who are drug users, the bar chart shows that you far more likely to contract covid 91 if you recive the vaccine. The numerical data shows the results in percentages. Within the placebo group 80.33% of individuals got infected with covid 91. While in the vaccine group 91.67% contracted covid 91. This indicates that receiving the vaccine as a drug user significantly increases the risk of contracted covid 91. The inferential data shows the Chi-Square P-Value is 1.414e-10, and the data also includes the fisher exact test that shows the P-Value is 3.261e-12 which is significantly lower than 0.05 which means we reject the null hypothesis. In summation these examples and simulations show that as a drug user you are far more likely to contract covid 91 if you receive the vaccine.   

## Overall conclusion 

Overall, upon revewing the data it is clear that receiving the vaccine will always have an affect on the person receiving it. The data shows that receiving the vaccine is generally effective i preventing the contraction of covid 91 if you are a male, female, or a member of the LGBTQ community. However, the opposite is true for people who are drug users. According to studies conducted you are at much higher risk of contracting covid91 if you are a drug user. Presumably the opposite effect of the vaccine's purpose.   











